version: '3.1'

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
